name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
variables:
  DEV_IMAGE_TAG: preview
  FBE_DEV_CI_CHANGES_IMAGE_TAG: fbedevpreview
  INTEGRATIONTEST_IoTHubEventHubConsumerGroup: reserved_integrationtest
  NET_SRV_VERSION: "1"
  PKT_FWD_VERSION: ""

pr:
  branches:
    include:
    - master
    - dev
    - fbe-dev-ci-changes
trigger:
  batch: true
  branches:
    include:
    - dev
    - fbe-dev-ci-changes
    - master

jobs:
- job: build_and_test
  condition: ne(variables['RunTestsOnly'], 'true') # do not run if RunTestsOnly == true
  displayName: Build and Test Solution
  continueOnError: false
  pool:
    vmImage: 'Ubuntu 16.04'   

  steps:
  - script: dotnet build --configuration $(buildConfiguration) ./LoRaEngine/LoRaEngine.sln
    displayName: Build LoRa Engine    
    enabled: false

  - script: dotnet build --configuration $(buildConfiguration) ./LoRaEngine/modules/LoRaSimulator/LoRaSimulator.sln
    displayName: Build LoRa Simulator
    enabled: false

  - script: |
      mkdir $(Build.SourcesDirectory)\results
      dotnet test --logger trx ./LoRaEngine/test/LoRaWanNetworkServer.Test/*.csproj
      dotnet test --logger trx ./LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaToolsTest/*.csproj
    displayName: Run unit test
    enabled: false

  - task: PublishTestResults@2
    displayName: 'Publish unit test results 2'
    enabled: false
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
  - bash: |
     getCILabelStatus=$(curl -s --head -w %{http_code} "https://api.github.com/repos/$BUILD_REPOSITORY_ID/labels/fullci" -o /dev/null)
     if $getCILabelStatus = "200" 
     then
       echo "##vso[task.setvariable variable=FullCI]true"
     fi
    displayName: Check for CI label build on PR
    condition: eq(variables['Build.Reason'], 'PullRequest')

  - bash: printenv
  
- job: full_ci_deploy
  displayName: Build, push and deploy IoT Edge Solution
  dependsOn: build_and_test
  condition: and(ne(variables['RunTestsOnly'], 'true'), and(succeeded(), or(eq(variables['FullCI'],'true'), in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/dev', 'refs/heads/fbe-dev-ci-changes'))))
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    IOT_DEPLOYMENT_ID: integrationtest
  
  steps:
  - bash: |
     if [ "$BUILD_SOURCEBRANCH" = "refs/heads/fbe-dev-ci-changes" ]; then
       echo "fbe-dev-ci-changes"
       IMAGE_TAG="$FBE_DEV_CI_CHANGES_IMAGE_TAG-"
     elif [ "$BUILD_SOURCEBRANCH" = "refs/heads/dev" ]; then
       echo "dev"
       IMAGE_TAG="$DEV_IMAGE_TAG-"
     elif [ "$BUILD_SOURCEBRANCH" = "refs/heads/master" ]; then
       echo "master"
       IMAGE_TAG=""
     elif [ "$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER" != "" ]; then
       echo "pull request"
       IMAGE_TAG="pr-$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER-"
     else
       echo "all others"
       IMAGE_TAG="custom-$BUILD_SOURCEBRANCHNAME-"
     fi
     echo "Using image tag prefix $IMAGE_TAG"
     IMAGE_TAG="$IMAGE_TAG$BUILD_BUILDID"
     echo "Using image tag $IMAGE_TAG"
     echo "##vso[task.setvariable variable=NET_SRV_VERSION]$IMAGE_TAG"
     echo "##vso[task.setvariable variable=PKT_FWD_VERSION]$IMAGE_TAG"      
     cp LoRaEngine/deployment.test.template.json LoRaEngine/deployment.template.json 
    displayName: Set Module version numbers and activate test template
    name: setImageTag

  - task: vsc-iot.iot-edge-build-deploy.custom-build-release-task.AzureIoTEdge@1
    displayName: "Build and Push IoT Edge Solution"
    env:
      AZURE_SUBSCRIPTIONID: $(AZURE_SUBSCRIPTIONID_SECRET)
      CONTAINER_REGISTRY_PASSWORD: $(CONTAINER_REGISTRY_PASSWORD_SECRET)
    inputs:
      azureSubscriptionEndpoint: IntegrationTestRG
      moduleJsons: 'modules/*/module.json'
      containerregistrytype: 'Azure Container Registry'
      azureContainerRegistry: '{"loginServer":"$(CONTAINER_REGISTRY_ADDRESS)", "id" : "/subscriptions/$(AZURE_SUBSCRIPTIONID)/resourceGroups/$(ACR_RG)/providers/Microsoft.ContainerRegistry/registries/$(ACR_NAME)"}'
      rootPath: ./LoRaEngine

  - task: vsc-iot.iot-edge-build-deploy.custom-build-release-task.AzureIoTEdge@1
    displayName: 'Azure IoT Edge - Deploy to integration test device $(INTEGRATIONTEST_LeafDeviceGatewayID)'
    inputs:
      action: 'Deploy to IoT Edge devices'
      azureSubscription: IntegrationTestRG
      iothubname: '$(INTEGRATIONTEST_IOTHUB_NAME)'
      deploymentid: '$(IOT_DEPLOYMENT_ID)'
      deviceOption: 'Single Device'
      deviceId: '$(INTEGRATIONTEST_LeafDeviceGatewayID)'
      rootPath: ./LoRaEngine

  - task: AzureCLI@1
    displayName: 'Waiting deployment $(IOT_DEPLOYMENT_ID) to be ready at $(INTEGRATIONTEST_LeafDeviceGatewayID)...'
    inputs:
      azureSubscription: IntegrationTestRG
      timeoutInMinutes: 30
      scriptLocation: inlineScript
      inlineScript: |
        az extension add --name azure-cli-iot-ext     
        until `az iot edge deployment show-metric --deployment-id $(IOT_DEPLOYMENT_ID) --metric-id reportedSuccessfulCount  --hub-name $(INTEGRATIONTEST_IOTHUB_NAME)|grep -q $(INTEGRATIONTEST_LeafDeviceGatewayID)`; do sleep 10 && echo wait; done

- job: test_runner_eu
  displayName: Run tests in device
  dependsOn: full_ci_deploy
  condition: or(succeeded(), eq(variables['RunTestsOnly'], 'true'))
  pool:    
    name: Default
    demands: Agent.OSArchitecture -equals ARM
  variables:      
    INTEGRATIONTEST_LeafDeviceSerialPort: "/dev/ttyACM0"
    INTEGRATIONTEST_IoTHubEventHubConsumerGroup: "reserved_integrationtest" 
  
  steps:
  - task: qetza.replacetokens.replacetokens-task.replacetokens@3
    displayName: 'Configure test in **/test/LoRaWan.IntegrationTest/appsettings.json'  
    inputs:
      targetFiles: '**/test/LoRaWan.IntegrationTest/appsettings.json'


  - task: DotNetCoreCLI@2
    displayName: 'Run integration test'
    enabled: true
    inputs:
      command: test
      projects: '**/test/LoRaWan.IntegrationTest/LoRaWan.IntegrationTest.csproj'
      arguments: '-p:ParallelizeTestCollections=false $(AdditionalIntegrationTestArguments)'

