name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
variables:
  VMYVAR: $MYVAR
  VPRID: $(System.PullRequest.PullRequestId)
  VREQUESTEDFOREMAIL: $(Build.RequestedForEmail)
pr:
  branches:
    include:
      - master
      - dev
      - fbe-dev-ci-changes
trigger:
  batch: true
  branches:
    include:
      - dev
      - master

jobs:
- job: buildAndTest
  displayName: Build and Test
  continueOnError: false
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    buildConfiguration: Release
    

  steps:
  - bash: printenv
    displayName: Show env variables    

  - script: dotnet build --configuration $(buildConfiguration) ./LoRaEngine/LoRaEngine.sln
    displayName: Build LoRa Engine    
    enabled: false

  - script: dotnet build --configuration $(buildConfiguration) ./LoRaEngine/modules/LoRaSimulator/LoRaSimulator.sln
    displayName: Build LoRa Simulator
    enabled: false

  - script: |
      mkdir $(Build.SourcesDirectory)\results
      dotnet test --logger trx ./LoRaEngine/test/LoRaWanNetworkServer.Test/*.csproj
      dotnet test --logger trx ./LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaToolsTest/*.csproj
    displayName: Run unit test
    enabled: false

  - task: PublishTestResults@2
    displayName: 'Publish unit test results 2'
    enabled: false
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
  
  - bash: |
     IMAGE_TAG="$IMAGE_TAG_PREFIX$BUILD_BUILDID"
     echo "Using image tag $IMAGE_TAG"
     echo "##vso[task.setvariable variable=NET_SRV_VERSION]$IMAGE_TAG"
     echo "##vso[task.setvariable variable=PKT_FWD_VERSION]$IMAGE_TAG"  
     cp LoRaEngine/deployment.test.template.json LoRaEngine/deployment.template.json 
    displayName: 'Set Module version numbers and activate test template'


  - bash: |
     if [ "$BUILD_SOURCEBRANCH" = "refs/heads/fbe-dev-ci-changes" ]; then
       echo "fbe-dev-ci-changes"
       IMAGE_TAG_PREFIX = "-fbedev-preview"
     elif [ "$BUILD_SOURCEBRANCH" = "refs/heads/dev" ]; then
       echo "dev"
       IMAGE_TAG_PREFIX = "-preview"
     elif [ "$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER" != "" ]; then
       echo "pull request"
       IMAGE_TAG_PREFIX = "-pr-$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER"
     fi
     echo "Using image tag prefix $IMAGE_TAG_PREFIX"
     IMAGE_TAG="$IMAGE_TAG_PREFIX$BUILD_BUILDID"
     echo "Using image tag $IMAGE_TAG"
     echo "##vso[task.setvariable variable=NET_SRV_VERSION]$IMAGE_TAG"
     echo "##vso[task.setvariable variable=PKT_FWD_VERSION]$IMAGE_TAG"      
     cp LoRaEngine/deployment.test.template.json LoRaEngine/deployment.template.json 
    displayName: Set Module version numbers and activate test template 2
    enabled: true
    condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/dev', 'refs/heads/fbe-dev-ci-changes'))




